#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "jwarsvadm" <<-EOSQL
    CREATE USER ujwarsvdev WITH ENCRYPTED PASSWORD 'jwarsvdev@123';
    CREATE USER ujwarsvprod WITH ENCRYPTED PASSWORD 'jwarsvprod@456';

    CREATE DATABASE jwarsv_db_dev;
    CREATE DATABASE jwarsv_db_prod;

    GRANT ALL PRIVILEGES ON DATABASE jwarsv_db_dev TO jwarsvadm;
    GRANT ALL PRIVILEGES ON DATABASE jwarsv_db_prod TO jwarsvadm;

    GRANT ALL PRIVILEGES ON DATABASE jwarsv_db_dev TO ujwarsvdev;
    GRANT ALL PRIVILEGES ON DATABASE jwarsv_db_prod TO ujwarsvprod;

    \c jwarsv_db_dev
    ALTER SCHEMA public OWNER TO ujwarsvdev;
    GRANT ALL PRIVILEGES ON SCHEMA public TO jwarsvadm;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ujwarsvdev;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ujwarsvdev;
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ujwarsvdev;

    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO ujwarsvdev;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO ujwarsvdev;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO ujwarsvdev;

    \c jwarsv_db_prod
    ALTER SCHEMA public OWNER TO ujwarsvprod;
    GRANT ALL PRIVILEGES ON SCHEMA public TO jwarsvadm;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ujwarsvprod;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ujwarsvprod;
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ujwarsvprod;

    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO ujwarsvprod;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO ujwarsvprod;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO ujwarsvprod;

EOSQL