#base
rootProject.name = jwarsv-core
version = 0.0.1-SNAPSHOT
group = br.com.bnuuy.jwar

#JVM
org.gradle.jvmargs=-Dfile.encoding=UTF-8

#java
java.sourceCompatibility = 17
java.targetCompatibility = 17

#spring profile
springProfile = dev

#Plugins
graalvmBuildtoolsNativePluginVersion = 0.10.3
hibernateOrmPluginVersion = 6.6.2.Final
springDepManagementPluginVersion = 1.1.6
springBootPluginVersion = 3.3.5
sonarPluginVersion = 3.1.1


#spring libs versions
springBootVersion = 3.3.5
springVersion = 6.2.0
springCloudVersion = 2023.0.3
springModulithVersion = 1.2.5

#external Libs versions
apacheCommons3Version = 3.17.0
apacheCommonsValidationVersion = 1.9.0
commonsIOVersion = 2.17.0
firebaseAdminVersion = 9.4.1
flywayVersion = 10.21.0

gsonVersion = 2.11.0
httpClient5Version = 5.3.1
hypersistenceUtilsHibernateVersion=3.5.2

jarkartaPersistenceApiVersion = 3.2.0
jarkartaValidationApiVersion = 3.1.0
jarkartaServletApiVersion = 6.0.0
jakartaXmlbindAnnotations = 2.15.2
jacksonVersion = 2.14.0
jacksonDataType8Version = 2.15.0

jjwtApi = 0.11.2
jjwtImpl = 0.11.2
jjwtJackson = 0.11.2

lombokVer = 1.18.30
mapstructVersion = 	1.5.5.Final
nettyCommonVersion = 4.1.115.Final
openCSVVersion = 5.8

postgreSqlVersion = 42.7.4

starkBankSdkVersion = 2.13.0
stripeSdkVersion = 28.3.0
sentryVersion = 6.30.0
sendGridVersion = 4.10.3

#tests
jacocoToolVersion=0.8.9
junitVersion = 5.10.0
mockitoVersio = 5.6.0