upstream backend-prod {
       server jwarsv-backend-app-prod:8080;
}

upstream backend-dev {
       server jwarsv-backend-app-dev:8081;
}

server {
#     listen       80;
    listen       443 ssl;
    ssl_certificate /etc/nginx/ssl/cloudflaresigned.crt;
    ssl_certificate_key /etc/nginx/ssl/cloudflaresigned.key;
    server_name  api.localhost.qa localhost qa-api.bnuuywar.com qa-api-v2.bnuuywar.com;

    # Add SSL options
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    index index.html;
    access_log /var/log/nginx/access-dev.log main;
    error_log  /var/log/nginx/error-dev.log warn;
    root /var/www/html/public;

    charset   utf-8;

    gzip on;
    gzip_vary on;
    gzip_disable "msie6";
    gzip_comp_level 6;
    gzip_min_length 1100;
    gzip_buffers 16 8k;
    gzip_proxied any;
    gzip_types
        text/plain
        text/css
        text/js
        text/xml
        text/javascript
        application/javascript
        application/x-javascript
        application/json
        application/xml
        application/xml+rss;

    location /api/ {
#         proxy_pass  http://host.docker.internal:8081; #only for local dev
        proxy_pass  http://backend-dev;
    }

    location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|svg|woff|woff2|ttf)\$ {
      expires 1M;
      access_log off;
      add_header Cache-Control "public";
    }

    location ~* \.(?:css|js)\$ {
      expires 7d;
      access_log off;
      add_header Cache-Control "public";
    }

    location ~ /\.ht {
        deny  all;
    }

}

server {
#     listen       80;
    listen       443 ssl;
    ssl_certificate /etc/nginx/ssl/cloudflaresigned.crt;
    ssl_certificate_key /etc/nginx/ssl/cloudflaresigned.key;
    server_name  api.localhost.prod api.bnuuywar.com api-v2.bnuuywar.com;

    # Add SSL options
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    index index.html;
    access_log /var/log/nginx/access-prod.log main;
    error_log  /var/log/nginx/error-prod.log warn;
    root /var/www/html/public;

    charset   utf-8;

    gzip on;
    gzip_vary on;
    gzip_disable "msie6";
    gzip_comp_level 6;
    gzip_min_length 1100;
    gzip_buffers 16 8k;
    gzip_proxied any;
    gzip_types
        text/plain
        text/css
        text/js
        text/xml
        text/javascript
        application/javascript
        application/x-javascript
        application/json
        application/xml
        application/xml+rss;

    location /api/ {
#         proxy_pass  http://host.docker.internal:8080; #only for local dev
        proxy_pass  http://backend-prod;
    }

    location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|svg|woff|woff2|ttf)\$ {
      expires 1M;
      access_log off;
      add_header Cache-Control "public";
    }

    location ~* \.(?:css|js)\$ {
      expires 7d;
      access_log off;
      add_header Cache-Control "public";
    }

    location ~ /\.ht {
        deny  all;
    }
}

server {
    listen 80;  # Listen on HTTP port
    server_name api.localhost.prod api.bnuuywar.com api-v2.bnuuywar.com api.localhost.qa localhost qa-api.bnuuywar.com qa-api-v2.bnuuywar.com;

    # Redirect all HTTP requests to HTTPS
    return 301 https://$host$request_uri;  # Use a 301 redirect
}
